FROM node
RUN useradd -ms /bin/bash admin
WORKDIR /app
COPY package.json .
RUN npm install --force
COPY . .
RUN chown -R admin:admin /app
RUN chmod 755 /app
USER admin
EXPOSE 3000
CMD ["npm", "run", "dev"]